### ISSUE TITLE
[Question] Contributing to the project

### ISSUE THREAD

**Issue by xaoc7** [gopythongo/aptly-api-client#76]
Hello,
I would like to contribute to that project or at least to try to. Can you please share if you have any specific requirements or guidelines to follow? What is exact process to contribute... make suggestion, create branch , PR etc...?

**Comment by jdelic** [comment]
Hey @xaoc7,

sorry for not replying sooner. I just looked at #78 and you're doing real good ;). In general, I want to keep test coverage at 100%, but you already did that and since there are very few contributors so far, I haven't given it much thought beyond that.

So for now "file a PR and discuss it with me as the sole maintainer" seems to be the process.

cheers
Jonas
